---

AWSTemplateFormatVersion: 2010-09-09

Description: AWS CloudFormation Stack for Running ElasticBeanstalk.

Parameters:

  EC2KeyName:
    Type: String
    Default: cloudavail-eb
    Description: EC2 KeyName for use with the EB EC2 Servers

Mappings: {}

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  PublicInternetRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicInternetRouteTable

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicInternetRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      CidrBlock: 10.0.0.0/25
      VpcId: !Ref VPC

  PublicSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1, !GetAZs "" ]
      CidrBlock: 10.0.0.128/25
      VpcId: !Ref VPC

  PublicSubnet01RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicInternetRouteTable
      SubnetId: !Ref PublicSubnet01

  PublicSubnet02RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicInternetRouteTable
      SubnetId: !Ref PublicSubnet02
  
  # ElasticBeanstalkPythonApplication:
  #   Type: AWS::ElasticBeanstalk::Application
  #   Properties:
  #     # note that if ApplicationName is set and is not unique you
  #     # will not able able to run a given stack multiple times
  #     ApplicationName: !Ref AWS::StackName
  #           
  # ElasticBeanstalkPythonConfigurationTemplate:
  #   Type: AWS::ElasticBeanstalk::ConfigurationTemplate
  #   Properties:
  #     ApplicationName: !Ref ElasticBeanstalkPythonApplication
  #     OptionSettings:
  #       - Namespace: aws:autoscaling:asg
  #         OptionName: MinSize
  #         Value: 1
  #       - Namespace: aws:autoscaling:asg
  #         OptionName: MaxSize
  #         Value: 1
  #       - Namespace: aws:autoscaling:launchconfiguration
  #         OptionName: EC2KeyName
  #         Value: !Ref EC2KeyName
  #       - Namespace: aws:autoscaling:launchconfiguration
  #         OptionName: InstanceType
  #         Value: t2.micro
  #       - Namespace: aws:elasticbeanstalk:environment
  #         OptionName: EnvironmentType
  #         Value: LoadBalanced
  #       - Namespace: aws:ec2:vpc
  #         OptionName: VPCId
  #         Value: !Ref VPC
  #       - Namespace: aws:ec2:vpc
  #         OptionName: Subnets
  #         # Value: !Join turns the individual subnets into a string
  #         Value: !Join [ ",", [ !Ref PublicSubnet01, !Ref PublicSubnet02 ] ]
  #       - Namespace: aws:ec2:vpc
  #         OptionName: AssociatePublicIpAddress
  #         Value: true
  #     SolutionStackName: 64bit Amazon Linux 2018.03 v2.7.7 running Python 2.7
# 
  # ElasticBeanstalkPythonEnvironment:
  #   Type: AWS::ElasticBeanstalk::Environment
  #   Properties:
  #     ApplicationName: !Ref ElasticBeanstalkApplication
  #     Description: ElasticBeanstalk Environment for Web
  #     EnvironmentName: !Sub ${AWS::StackName}-Web
  #     TemplateName: !Ref ElasticBeanstalkWebConfigurationTemplate

Outputs: {}
